name: Build Flutter Release APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'

      # Decode keystore file from GitHub secret
      - name: Decode keystore
        working-directory: habittracker/everbloom/android/app
        run: echo "$KEYSTORE_BASE64" | base64 --decode > release-keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # Install dependencies
      - name: Get dependencies
        working-directory: habittracker/everbloom
        run: flutter pub get

      # Build release APK
      - name: Build release APK
        working-directory: habittracker/everbloom
        run: flutter build apk --release --no-shrink
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Upload built APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: habittracker/everbloom/build/app/outputs/flutter-apk/app-release.apk
